### ISSUE TITLE
PyPi lists LICENSE as MIT

### ISSUE THREAD

**Issue by jcollard** [tomgross/pycloud#15]
When checking the LICENSE from command line or via PyPi site, this library shows up as MIT but README shows it is GPLv2 License which is quite different.

![image](https://user-images.githubusercontent.com/3529380/54314102-27286f00-45b1-11e9-800e-d8b49d1e2236.png)

Thanks.

**Comment by tomgross** [comment]
The licences is MIT. It was correct in the setup.py metadata and the docs/LICENSE.rst but not in the README. Thanks @jcollard for pointing that out. 

It's fixed in https://github.com/tomgross/pycloud/commit/1b0d9de6521904dcdc3ca3295f544008065e9e4e

**Comment by jcollard** [comment]
@tomgross it should also be noted that it still shows GPLv2 on the PyPi page documentation.

https://pypi.org/project/pcloud/

![image](https://user-images.githubusercontent.com/3529380/55829449-adff3780-5adc-11e9-9dab-da59993c3cba.png)
